name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: catppuccin/setup-whiskers@v2.0.0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          cache: pnpm
          node-version: 22
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
        working-directory: ./packages/catppuccin-starlight
